
/**
* ChatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* jeudi 25 septembre 2014 16 h 16 CEST
*/

public final class ChatHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat value = null;

  public ChatHolder ()
  {
  }

  public ChatHolder (Chat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatHelper.type ();
  }

}
