typedef sequence<string> Clients;
typedef sequence<string> Messages;


interface Dialogue
{

	void sendMessage(in string to, in string message);
	Messages getMessages();
	Clients getClients();
	void disconnect();

};


interface Connection
{
	Dialogue connect(in string nickname);

};
