
/**
* Chat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* mardi 14 octobre 2014 14 h 54 CEST
*/

public interface Chat extends ChatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Chat
