
/**
* ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* jeudi 25 septembre 2014 16 h 16 CEST
*/

public interface ChatOperations 
{
  void connect (String pseudo);
  void disconnect (String pseudo);
  String[] getClients ();
  void sendMessage (String from, String to, String message);
  String getMessage (String pseudo);
} // interface ChatOperations
