
/**
* ClientsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* jeudi 25 septembre 2014 16 h 16 CEST
*/

public final class ClientsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ClientsHolder ()
  {
  }

  public ClientsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientsHelper.type ();
  }

}
