
/**
* ConnectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* mardi 14 octobre 2014 15 h 47 CEST
*/

public interface ConnectionOperations 
{
  Dialogue connect (String nickname);
} // interface ConnectionOperations
