
/**
* DialogueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* mardi 14 octobre 2014 15 h 23 CEST
*/

public interface DialogueOperations 
{
  void sendMessage (String to, String message);
  String[] getMessages ();
  String[] getClients ();
  void disconnect ();
} // interface DialogueOperations
